{% set name = "pysisso" %}
{% set version = "0.3.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/pysisso-{{ version }}.tar.gz
  sha256: 3789d20a2273c4bd9d9f5df1f044cb901420f14742a0bfbe8c89a6c4b62e1be8

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.6,<4.0
    - poetry-core >=1.0.0
    - pip
  run:
    - python >=3.6.1,<4.0.0
    - pandas >=1.0.5,<2.0.0
    - monty >=3.0.4,<5
    - custodian >=2020.4.27,<2021.0.0
    - scikit-learn >=0.23.1,<0.24.0

test:
  imports:
    - pysisso
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/Matgenix/pysisso/
  summary: Python interface to the SISSO (Sure Independence Screening and Sparsifying Operator) method.
  license: EPL-2.0
  license_file: LICENSE.rst

extra:
  recipe-maintainers:
    - jan-janssen
